version: "1"
services:
  app1:
    build: .
    environment:
      - APP_NAME=App_1
    ports:
      - 3001:3000
  app2:
    build: .
    environment:
      - APP_NAME=App_2
    ports:
      - 3002:3000
  app3:
    build: .
    environment:
      - APP_NAME=App_3
    ports:
      - 3003:3000
